#!/usr/bin/env bash

# Shared paths for the current scLC_ICI_PBMC workflows.
# On the server, clone this repository to:
#   /share/home/rzli/scLC_ICI_PBMC
# Every value can be overridden before this file is sourced.

_SCLC_CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

: "${SCLC_PROJECT_ROOT:=${_SCLC_CONFIG_DIR}}"
: "${SCLC_DATA_ROOT:=/share/LCZX_Data/data}"
: "${SCLC_REF_ROOT:=/share/LCZX_Data/ref}"
: "${SCLC_CONDA_ROOT:=/share/home/rzli/miniconda3}"

: "${SCLC_METHSCAN_DATE:=20260815}"
: "${SCLC_METHYLVI_DATE:=20260816}"
: "${SCLC_SCANPY_DATE:=20260815}"

: "${SCLC_ALLCOOLS_ROOT:=${SCLC_DATA_ROOT}/allcools}"
: "${SCLC_MATRIX_ROOT:=${SCLC_DATA_ROOT}/matrix}"

: "${SCLC_METHSCAN_ROOT:=${SCLC_PROJECT_ROOT}/Methscan/${SCLC_METHSCAN_DATE}}"
: "${SCLC_METHSCAN_SCRIPTS:=${SCLC_METHSCAN_ROOT}/Scripts}"
: "${SCLC_METHSCAN_RESULTS:=${SCLC_METHSCAN_ROOT}/Results}"

: "${SCLC_METHYLVI_ROOT:=${SCLC_PROJECT_ROOT}/MethylVI/${SCLC_METHYLVI_DATE}}"
: "${SCLC_METHYLVI_SCRIPTS:=${SCLC_METHYLVI_ROOT}/Scripts}"
: "${SCLC_METHYLVI_RESULTS:=${SCLC_METHYLVI_ROOT}/Results}"
: "${SCLC_METHYLVI_SUPPLEMENTARY:=${SCLC_METHYLVI_ROOT}/Supplementary_materials}"

: "${SCLC_SCANPY_ROOT:=${SCLC_PROJECT_ROOT}/Scanpy/${SCLC_SCANPY_DATE}}"
: "${SCLC_SCANPY_SCRIPTS:=${SCLC_SCANPY_ROOT}/Scripts}"
: "${SCLC_SCANPY_RESULTS:=${SCLC_SCANPY_ROOT}/Results}"
: "${SCLC_SCANPY_DOUBLET_METHODS:=${SCLC_SCANPY_RESULTS}/doublet_methods}"
: "${SCLC_SCANPY_SCRUBLET_ANNOTATION:=${SCLC_SCANPY_DOUBLET_METHODS}/scrublet/annotation/02_cell_annotation_all_cells.csv}"
: "${SCLC_SCANPY_SCRUBLET_CLEAN_ANNOTATION:=${SCLC_SCANPY_DOUBLET_METHODS}/scrublet/annotation/02_cell_annotation_clean_cells.csv}"
: "${SCLC_SCANPY_DOUBTFINDER_ANNOTATION:=${SCLC_SCANPY_DOUBLET_METHODS}/doubletfinder/annotation/02_cell_annotation_all_cells.csv}"
: "${SCLC_SCANPY_DOUBTFINDER_CLEAN_ANNOTATION:=${SCLC_SCANPY_DOUBLET_METHODS}/doubletfinder/annotation/02_cell_annotation_clean_cells.csv}"
# Legacy single-result paths are retained so existing Methscan/MethylVI jobs do not
# silently switch methods. New jobs should explicitly select one method above.
: "${SCLC_SCANPY_ANNOTATION:=${SCLC_SCANPY_RESULTS}/annotation/02_cell_annotation_all_cells.csv}"
: "${SCLC_SCANPY_CLEAN_ANNOTATION:=${SCLC_SCANPY_RESULTS}/annotation/02_cell_annotation_clean_cells.csv}"

export SCLC_PROJECT_ROOT SCLC_DATA_ROOT SCLC_REF_ROOT SCLC_CONDA_ROOT
export SCLC_METHSCAN_DATE SCLC_METHYLVI_DATE SCLC_SCANPY_DATE
export SCLC_ALLCOOLS_ROOT SCLC_MATRIX_ROOT
export SCLC_METHSCAN_ROOT SCLC_METHSCAN_SCRIPTS SCLC_METHSCAN_RESULTS
export SCLC_METHYLVI_ROOT SCLC_METHYLVI_SCRIPTS SCLC_METHYLVI_RESULTS
export SCLC_METHYLVI_SUPPLEMENTARY
export SCLC_SCANPY_ROOT SCLC_SCANPY_SCRIPTS SCLC_SCANPY_RESULTS
export SCLC_SCANPY_DOUBLET_METHODS
export SCLC_SCANPY_SCRUBLET_ANNOTATION SCLC_SCANPY_SCRUBLET_CLEAN_ANNOTATION
export SCLC_SCANPY_DOUBTFINDER_ANNOTATION SCLC_SCANPY_DOUBTFINDER_CLEAN_ANNOTATION
export SCLC_SCANPY_ANNOTATION SCLC_SCANPY_CLEAN_ANNOTATION

unset _SCLC_CONFIG_DIR
