#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/00_config.sh"
cd "$SCLC_SCANPY_ROOT"

# 整合阶段：所有数值库限制为单线程
limit_threads 1 OPENBLAS_NUM_THREADS GOTO_NUM_THREADS OMP_NUM_THREADS OMP_THREAD_LIMIT \
    MKL_NUM_THREADS NUMEXPR_NUM_THREADS VECLIB_MAXIMUM_THREADS BLIS_NUM_THREADS \
    NUMBA_NUM_THREADS LOKY_MAX_CPU_COUNT
export OMP_DYNAMIC=FALSE MKL_DYNAMIC=FALSE

"$SCANPY_PYTHON" "$SCRIPT_DIR/03_integration.py"
